#!/usr/bin/env bash
# a script display information about the subdomains

dig_domain () {
    string=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tail -1)
    echo "$2 $string" | awk '{print "The subdomain " $1 " is a " $5 " record and points to " $6}'
}

if [ "$#" == 1 ]
then
  dig_domain "$1" "www"
  dig_domain "$1" "lb-01"
  dig_domain "$1" "web-01"
  dig_domain "$1" "web-02"
elif [ "$#" == 2 ]
then
  dig_domain "$1" "$2"
fi