#!/usr/bin/env bash
# Server-01 login commands

# Setting up the SSH-agent
eval "$(ssh-agent)"

# Path to IdentityFile (private key)
ssh-add ~/.ssh/id_rsa

# Username and IP Address
ssh ubuntu@54.86.197.47
