#!/usr/bin/env bash
# This script is displaying 1-100,fizz, FizzBuzz and Buzz

num=1
while ((num <= 100)); do
	if ((num % 3 == 0 && num % 5 == 0)); then
		echo "FizzBuzz"
	elif ((num % 3 == 0)); then
		echo "Fizz"
	elif ((num % 5 == 0)); then
		echo "Buzz"
	else
		echo $num
	fi
	((num++))
done
