#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
var=1
while ((var <= 20)); do
	case $var in
		4)
			echo $var
			echo "bad luck from China"
			;;
		9)
			echo $var; echo "bad luck from Japan"
			;;
		17)
			echo "$var"; echo "bad luck from Italy"
			;;
		*)
			echo "$var"
			;;
	esac
	((var++))
done
