#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
hours=0
mins=1

while ((hours <= 12))
do
	echo "Hour: $hours"
	while ((mins < 60))
	do
		echo $mins
		((mins++))
	done
	mins=1	
	((hours++))
done
