#!/usr/bin/env bash
# Bash script that configures an Ubuntu server with the below requirements.

# Backup the existing /etc/hosts file
cp /etc/hosts ~/hosts.bak

# Modify localhost entry
sed -i '/^127.0.0.1\s\+localhost/d' ~/hosts.bak
echo "127.0.0.2 localhost" >> ~/hosts.bak

# Modify facebook.com entry
sed -i '/^8.8.8.8\s\+facebook.com/d' ~/hosts.bak
echo "8.8.8.8 facebook.com" >> ~/hosts.bak

# Apply the new /etc/hosts configuration
sudo cp -f ~/hosts.bak /etc/hosts
