#!/usr/bin/env bash
# Script that displays all active IPv4 IPs on a machine

# Using ifconfig to find IPv4 addresses
ifconfig | grep -Eo "inet (addr:)?([0-9]*\.){3}[0-9]*" | grep -v "127.0.0.1" | awk '{ print $2 }'
